### ISSUE TITLE
Some links are broken (only relative)

### ISSUE THREAD

**Issue by Matthias84** [kaffeekarte/kaffeekarte.github.io#1]
For example: https://kaffeekarte.github.io/#13&54.13740042972796&12.00187683105469

**Comment by Matthias84** [comment]
Sorry, this was my fault. I tried to link to a single POI, that refers to a broken link:
https://kaffeekarte.github.io/#15&54.13833066122407&12.093586921691896 (at Schmarl Dorf)

**Comment by ValorNaram** [comment]
yes, this is not possible and in future It's not meant to be possible.

**Comment by Matthias84** [comment]
Well, I guess I wasn't pretty skilled, to explain you whats the bug. So here my second attempt:

The popup can contain broken links to websites of the POIs. For example 

> https://kaffeekarte.github.io/www.schokoladerie.com

It's [this POI node](https://www.openstreetmap.org/node/5450993210) and as you see, they are just relative to your URL, instead of the absolute URL.

**Comment by ValorNaram** [comment]
Fix available, will be applied in new version of Kaffeekarte
