### ISSUE TITLE
Verbesserung des "Lupenmenü"'s

### ISSUE THREAD

**Issue by mondstern** [kaffeekarte/kaffeekarte.github.io#10]
es geht um das menü wo die lupe rechts zu sehen ist, wo der ort eingetragen und auch andere felder angeklickt werden können.
da ich die kaffeekarte jeden tag benutze bzw brauche, habe ich gemerkt das es umständlich ist, wenn das ein Popup-Menü ist, bzw wenn man am pc sitzt und ide maus bewegt ist das Popup-Menü zack weg.
ich finde ein statisches "ort-suchenfeld" besser. so wie es bei der ersten ursprungs karte war bzw so wie es bei der unterkunftskarte ist.
die anderen felder (wie togo) kann da entfernt werden. wenn auf der README.md genau steht, welche tags ausgewertet werden, reicht das doch. wenn man weiss was angezeigt wird kann es ja auch so getaggt werden.
wickeltisch auswerten passt auch besser auf die Baby-Karte als auf die kaffeekarte.
also reicht eigentlich ein statisches ort-suchenfeld, 
und das "über das projekt" könnte noch zu der Leaflet zeile rechts unten dazu.

**Comment by ValorNaram** [comment]
Änderungswünsche teilweise übernommen
