### ISSUE TITLE
some more attributes

### ISSUE THREAD

**Issue by Matthias84** [kaffeekarte/kaffeekarte.github.io#2]
I suggest to include some more tags, that bring up more details of the POI:
* wifi
* smoking
* if pets allowed

EDIT BY VALOR NARAM: Removed `takeaway` and `outdoor_seating` since they are available throw the filter function.

**Comment by ValorNaram** [comment]
_outdoor-seating_ and _takeaway_ are included within Kaffeekarte. You can reach them via the filter (clicking on the right side on the search button and than clicking "Außenbereich" or "To Go" or both.

**Comment by Matthias84** [comment]
How about adding some pictograms at the POI popup menus? Apps as OSMand use this visual pattern to bring up that information.

**Comment by ValorNaram** [comment]
What kind of piktograms and for which purpose?

**Comment by ValorNaram** [comment]
`takeaway` and `outdoor_seating` are available throw the filter function.

**Comment by ValorNaram** [comment]
Found no tag that states, if pets are allowed or denied.

**Comment by Matthias84** [comment]
https://wiki.openstreetmap.org/wiki/Key:dog

**Comment by ValorNaram** [comment]
The key `dog` isn't widely used.
To clarify: I only implement frequently used keys in order to keep the UI clean and simple. If I would approve and implement all feature requests, I end up with a non user-friendly user interface

**Comment by ValorNaram** [comment]
Can you please show me in which cases the `smoking` tag is used in real, because I didn't find the tag on any cafè I checked.

**Comment by Matthias84** [comment]
I just know one cafe at my town that is dedicated to smokers (only).
You can see, that this tag combination is as same as popular as e.g. outdoor_seating:
https://taginfo.openstreetmap.org/tags/amenity=cafe#combinations

**Comment by ValorNaram** [comment]
The tag `smoking` has been implemented. A smoking icon on the POI details view indicates, if smoking is allowed.

**Comment by ValorNaram** [comment]
The tag `internet_access` has been implemented. This means Kaffeekarte shows you a wifi icon in the POI details view, if POI has a hotspot.

**Comment by ValorNaram** [comment]
Key `dog` implemented. This means Kaffeekarte will show you a dog icon in the POI details view, if POI allows to take a dog with.
